import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useAuth } from "../context/AuthContext";
import React from "react";


const API = `${import.meta.env.VITE_API_URL}/api`;
const tabs = ["Overview", "Posts", "Stats", "Recently Played", "Top Artists", "Top Songs", "Music DNA", "Achievements", "Settings"];
const initials = (name = "You") => name.split(" ").map((part) => part[0]).join("").slice(0, 2);
const Avatar = ({ user, large = false }) => user?.avatar ? <img className={large ? "profile-avatar large" : "profile-avatar"} src={user.avatar} alt="" /> : <span className={large ? "profile-avatar large" : "profile-avatar"}>{initials(user?.name)}</span>;
const statIcons = ["✦", "♫", "◌", "♡", "◷", "◉"];

export default function MyProfile() {
  const { token } = useAuth();
  const [user, setUser] = useState(null); const [insights, setInsights] = useState(null); const [posts, setPosts] = useState([]);
  const [matches, setMatches] = useState([]); const [tab, setTab] = useState("Overview"); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(false); const [bio, setBio] = useState("");
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token]);
  const load = async () => { setLoading(true); try { const [me, data, feed, board] = await Promise.all([fetch(`${API}/user/me`, { headers }), fetch(`${API}/social/insights`, { headers }), fetch(`${API}/posts`, { headers }), fetch(`${API}/social/leaderboard`, { headers })]); const meJson = me.ok ? await me.json() : null; setUser(meJson); setBio(meJson?.bio || "Music keeps the memories we forget to save."); setInsights(data.ok ? await data.json() : null); const postData = feed.ok ? await feed.json() : []; setPosts(postData.filter((post) => post.user?._id === meJson?._id)); setMatches(board.ok ? await board.json() : []); } finally { setLoading(false); } };
  useEffect(() => { if (token) load(); }, [token]);
  const saveBio = async () => { const response = await fetch(`${API}/social/profile`, { method:"PATCH", headers:{...headers,"Content-Type":"application/json"}, body:JSON.stringify({ bio }) }); if (response.ok) { setUser((current) => ({...current,bio})); setEditing(false); } };
  const topArtists = user?.stats?.shortTerm?.topArtists || []; const topTracks = user?.stats?.shortTerm?.topTracks || []; const recent = user?.recentlyPlayed || [];
  const dna = insights?.musicDna || {}; const genres = insights?.topGenres || []; const personality = insights?.personality || "The Explorer"; const mood = insights?.mood || "Curious";
  const statistics = [{ label:"Top artist", value:insights?.favoriteArtist?.name || topArtists[0]?.name || "—" }, { label:"Top song", value:insights?.favoriteTrack?.name || topTracks[0]?.name || "—" }, { label:"Favorite genre", value:genres[0] || "Discovering" }, { label:"Current mood", value:mood }, { label:"Music personality", value:personality }, { label:"Posts", value:posts.length }, { label:"Total likes", value:posts.reduce((sum,p)=>sum+(p.likes?.length||0),0) }, { label:"Recently played", value:recent.length }];
  if (loading) return <div className="profile-skeleton"><i /><i /><i /><i /></div>;
  if (!user) return <div className="profile-empty"><span>♫</span><h2>We couldn’t load your profile.</h2><button onClick={load}>Try again</button></div>;
  const panel = { initial:{opacity:0,y:12}, animate:{opacity:1,y:0}, exit:{opacity:0,y:-8}, transition:{duration:.24} };
  return <section className="profile-premium">
    <motion.div className="profile-cover" initial={{opacity:0,scale:1.03}} animate={{opacity:1,scale:1}} transition={{duration:.65}}><i className="cover-orb one"/><i className="cover-orb two"/><i className="cover-grid"/></motion.div>
    <div className="profile-intro"><motion.div initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:170}} className="avatar-glow"><Avatar user={user} large /></motion.div><div className="profile-name"><p className="eyebrow">LISTENING SINCE {new Date(user.createdAt).getFullYear()}</p><h1>{user.name}</h1><p className="handle">@{user.name?.toLowerCase().replace(/\s+/g, ".")}</p><div className="badge-row"><span>🎧 Indie Lover</span><span>🌙 Night Listener</span><span>⭐ Top Listener</span></div></div><div className="profile-actions"><button onClick={() => setEditing(true)}>Edit profile</button><button onClick={() => navigator.clipboard?.writeText(window.location.href)}>↗ Share</button></div></div>
    <div className="profile-bio"><span>“</span><p>{user.bio || bio}</p><small>{personality} · ranked among your closest listeners</small></div>
    <div className="profile-tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab===item} key={item} onClick={() => setTab(item)} className={tab===item ? "active" : ""}>{item}</button>)}</div>
    <AnimatePresence mode="wait"><motion.div key={tab} {...panel}>
      {tab === "Overview" && <><div className="profile-summary">{statistics.slice(0,6).map((stat,index)=><motion.article whileHover={{y:-5,scale:1.015}} key={stat.label}><span>{statIcons[index]}</span><p>{stat.label}</p><h3>{stat.value}</h3></motion.article>)}</div><div className="profile-grid"><section className="glass-section feature"><p className="eyebrow">YOUR SOUND</p><h2>{personality}</h2><p>{insights?.description || "A listening identity built from the music you return to."}</p><div className="genre-pills">{genres.map((genre)=><span key={genre}>{genre}</span>)}</div></section><section className="glass-section match-spotlight"><p className="eyebrow">MUSIC TWIN</p>{matches[0] ? <><Avatar user={matches[0]}/><h2>{matches[0].name} <b>{matches[0].compatibility.score}%</b></h2><p>{matches[0].compatibility.sharedArtists?.slice(0,2).join(" · ") || matches[0].personality}</p></> : <div className="tiny-empty">We’re finding your music twin.</div>}</section></div><MusicDna dna={dna}/></>}
      {tab === "Posts" && <Posts posts={posts} user={user}/>} {tab === "Stats" && <div className="profile-summary all">{statistics.map((stat,index)=><article key={stat.label}><span>{statIcons[index%statIcons.length]}</span><p>{stat.label}</p><h3>{stat.value}</h3></article>)}</div>}
      {tab === "Recently Played" && <Timeline items={recent} fallback={topTracks}/>} {tab === "Top Artists" && <MusicGrid title="Your top artists" items={topArtists} artist />} {tab === "Top Songs" && <MusicGrid title="Songs on repeat" items={topTracks}/>} {tab === "Music DNA" && <MusicDna dna={dna} full/>}
      {tab === "Achievements" && <Achievements/>} {tab === "Settings" && <section className="glass-section settings"><p className="eyebrow">PROFILE CUSTOMIZATION</p><h2>Make this space yours.</h2><label>Bio<textarea value={bio} onChange={(e)=>setBio(e.target.value)} /></label><button onClick={saveBio}>Save profile</button></section>}
    </motion.div></AnimatePresence>
    {editing && <div className="modal-backdrop"><motion.div initial={{scale:.94,opacity:0}} animate={{scale:1,opacity:1}} className="profile-edit"><button className="close" onClick={()=>setEditing(false)}>×</button><p className="eyebrow">EDIT PROFILE</p><h2>Tell your story</h2><textarea value={bio} onChange={(e)=>setBio(e.target.value)}/><button onClick={saveBio}>Save changes</button></motion.div></div>}
  </section>;
}

function MusicDna({ dna, full }) { const entries=Object.entries(dna); return <section className={full ? "glass-section dna-full" : "glass-section dna-section"}><div><p className="eyebrow">MUSIC DNA</p><h2>What powers your listening.</h2><p>Estimated from your artists, genres, and listening patterns.</p></div><div className="dna-visual"><div className="radar"><i/><i/><i/><b>DNA</b></div><div className="dna-list">{entries.map(([name,value])=><div key={name}><span>{name}<b>{value}{name==="tempo"?" BPM":"%"}</b></span><i><em style={{width:`${Math.min(100,name==="tempo"?value/1.8:value)}%`}}/></i></div>)}</div></div></section> }
function MusicGrid({ title, items, artist }) { return <section><div className="tab-heading"><p className="eyebrow">YOUR LIBRARY</p><h2>{title}</h2></div><div className="music-grid">{items.length?items.map((item,index)=><motion.article whileHover={{y:-7}} key={`${item.name}-${index}`}><div className="artwork">{item.image?<img src={item.image} alt=""/>:<span>♫</span>}<button>▶</button></div><h3>{item.name}</h3>{!artist&&<p>{item.artist}</p>}<small>#{index+1} this month</small></motion.article>):<div className="profile-empty">Your next favorite is waiting to be played.</div>}</div></section> }
function Timeline({ items, fallback }) { const list=items.length?items:fallback; return <section className="timeline"><div className="tab-heading"><p className="eyebrow">LISTENING HISTORY</p><h2>Your recent timeline</h2></div>{list.length?list.slice(0,8).map((track,index)=><motion.article initial={{opacity:0,x:-15}} animate={{opacity:1,x:0}} transition={{delay:index*.05}} key={`${track.name}-${index}`}><i/><span>{String(index+1).padStart(2,"0")}</span><div>{track.image&&<img src={track.image} alt=""/>}<div><h3>{track.name}</h3><p>{track.artist || "Recently played"}</p></div></div><small>{index<2?"Today":`${index+1} days ago`}</small></motion.article>):<div className="profile-empty">Start listening to create your timeline.</div>}</section> }
function Posts({ posts, user }) { return <section><div className="tab-heading"><p className="eyebrow">FROM YOUR FEED</p><h2>Music moments</h2></div><div className="profile-posts">{posts.length?posts.map((post)=><motion.article whileHover={{y:-5}} key={post._id}><div><Avatar user={user}/><span><b>{user.name}</b><small>{new Date(post.createdAt).toLocaleDateString()}</small></span></div><section><i>♫</i><p>{post.caption}</p></section><footer><button>♡ {post.likes?.length||0}</button><button>◌ {post.comments?.length||0}</button><button>↗</button><button>⌑</button></footer></motion.article>):<div className="profile-empty"><span>♫</span><h2>No posts yet.</h2><p>Share your music taste with the world.</p></div>}</div></section> }
function Achievements() { const badges=[["🎧","Indie Explorer","Unlocked"],["🌙","Night Owl","Unlocked"],["🎸","Rock Veteran","In progress"],["🎹","Jazz Expert","Discover more"]]; return <section><div className="tab-heading"><p className="eyebrow">YOUR COLLECTION</p><h2>Achievements</h2></div><div className="level-card"><div><p>LEVEL 12</p><h2>Music Explorer</h2><small>2,450 / 3,000 XP</small></div><i><em/></i></div><div className="achievement-grid">{badges.map(([icon,name,status],index)=><motion.article initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:index*.08}} key={name}><span>{icon}</span><h3>{name}</h3><p>{status}</p></motion.article>)}</div></section> }
