import express from "express";
import { verifyToken } from "../middleware/auth.middleware.js";
import { asyncHandler } from "../middleware/asyncHandler.js";
import { validateObjectId } from "../middleware/validateObjectId.js";
import { interactionLimiter } from "../middleware/security.middleware.js";
import { clearNotifications, deleteNotification, listNotifications, markAllRead, markRead } from "../controllers/notification.controller.js";
const router = express.Router(); router.use(verifyToken);
router.get("/", asyncHandler(listNotifications)); router.patch("/read-all", interactionLimiter, asyncHandler(markAllRead)); router.delete("/", interactionLimiter, asyncHandler(clearNotifications));
router.patch("/:notificationId/read", validateObjectId("notificationId"), interactionLimiter, asyncHandler(markRead)); router.delete("/:notificationId", validateObjectId("notificationId"), interactionLimiter, asyncHandler(deleteNotification));
export default router;
