const normalise = (value) => String(value || "").trim().toLowerCase();
const unique = (items) => [...new Set(items.filter(Boolean))];
const overlap = (left, right) => left.filter((item) => new Set(right).has(item));
const percent = (left, right) => !left.length || !right.length ? 0 : Math.round((overlap(left, right).length / Math.max(left.length, right.length)) * 100);

export function profileSignals(user) {
  const stats = user.stats?.shortTerm || user.stats?.mediumTerm || {};
  const artists = stats.topArtists || [], tracks = stats.topTracks || [];
  const genres = unique([...artists.flatMap((artist) => artist.genres || []), ...(user.analysis?.topGenres || [])].map(normalise));
  return { artists, tracks, genres, artistNames: unique(artists.map((a) => normalise(a.name))), trackNames: unique(tracks.map((t) => normalise(t.name))), recent: unique((user.recentlyPlayed || []).map((t) => normalise(t.name))) };
}
export function getMood(user) { if (user.analysis?.mood) return user.analysis.mood; const text = [...profileSignals(user).genres, ...profileSignals(user).artistNames].join(" "); if (/sad|dream|indie|folk|lana|clairo/.test(text)) return "Melancholic"; if (/dance|electronic|party|hip hop|rap/.test(text)) return "Energetic"; if (/lo-fi|jazz|ambient|acoustic/.test(text)) return "Relaxed"; return "Curious"; }
export function getPersonality(user) { if (user.analysis?.personality) return user.analysis.personality; const text = [...profileSignals(user).genres, ...profileSignals(user).artistNames].join(" "); if (/bedroom|dream|indie|clairo|beabadoobee/.test(text)) return "The Dreamer"; if (/hip hop|rap|trap/.test(text)) return "The Storyteller"; if (/electronic|dance|house|techno/.test(text)) return "The Night Owl"; if (/jazz|soul|r&b/.test(text)) return "The Chill Listener"; if (/rock|metal|punk/.test(text)) return "The Rock Veteran"; if (/pop|taylor|olivia/.test(text)) return "The Pop Addict"; return "The Explorer"; }
export function getMusicDna(user) { const text = [...profileSignals(user).genres, ...profileSignals(user).artistNames].join(" "); const has = (p) => p.test(text); const dna = { energy:52,danceability:50,positivity:51,acousticness:34,instrumentalness:18,tempo:112 }; if(has(/electronic|dance|house|techno|hip hop|rap/)){dna.energy+=24;dna.danceability+=28;dna.tempo+=14;} if(has(/indie|dream|bedroom|folk|acoustic|lo-fi/)){dna.acousticness+=31;dna.energy-=13;dna.positivity-=6;} if(has(/jazz|classical|ambient|instrumental/)){dna.instrumentalness+=30;dna.acousticness+=17;dna.tempo-=10;} if(has(/pop|disco|funk/)){dna.positivity+=19;dna.danceability+=12;} return Object.fromEntries(Object.entries(dna).map(([k,v])=>[k,Math.max(0,Math.min(k==="tempo"?180:100,v))])); }
export function genreDistribution(user) { const genres=profileSignals(user).genres; return genres.slice(0,6).map((name,index)=>({name,percentage:Math.max(8,Math.round((1-index*.12)*100/Math.min(genres.length,4)))})); }
export function analyseUser(user) { const signals=profileSignals(user),personality=getPersonality(user),mood=getMood(user),averageFeatures=getMusicDna(user); return {personality,mood,musicProfile:`A ${personality.toLowerCase()} with a ${mood.toLowerCase()} listening mood.`,topGenres:signals.genres,favoriteArtist:signals.artists[0]||null,favoriteSong:signals.tracks[0]||null,averageFeatures,genreDistribution:genreDistribution(user)}; }
export function compatibility(user,candidate) { const mine=profileSignals(user),theirs=profileSignals(candidate),sharedArtists=overlap(mine.artistNames,theirs.artistNames),sharedTracks=overlap(mine.trackNames,theirs.trackNames),sharedGenres=overlap(mine.genres,theirs.genres),sharedRecent=overlap(mine.recent,theirs.recent),myDna=getMusicDna(user),theirDna=getMusicDna(candidate); const breakdown={topArtists:percent(mine.artistNames,theirs.artistNames),topSongs:percent(mine.trackNames,theirs.trackNames),genres:percent(mine.genres,theirs.genres),mood:getMood(user)===getMood(candidate)?100:42,personality:getPersonality(user)===getPersonality(candidate)?100:48,listeningHistory:percent(mine.recent,theirs.recent)}; const score=Math.round(breakdown.topArtists*.30+breakdown.topSongs*.20+breakdown.genres*.22+breakdown.mood*.10+breakdown.personality*.10+breakdown.listeningHistory*.08); const reasons=[sharedArtists.length&&`You both love ${sharedArtists.slice(0,2).join(" and ")}.`,sharedGenres.length&&`You both mostly listen to ${sharedGenres.slice(0,2).join(" and ")}.`,getMood(user)===getMood(candidate)&&`You share a ${getMood(user).toLowerCase()} listening mood.`,`Your estimated music energy differs by only ${Math.abs(myDna.energy-theirDna.energy)}%.`].filter(Boolean); return {score,breakdown,reasons,sharedArtists,sharedTracks,sharedGenres,sharedRecent,personality:getPersonality(candidate),mood:getMood(candidate)}; }
